<!--#include file="../../AsaiData/cf.asp"--><!--#include file="../../AsaiInc/incba.asp"--><%
Call esq()
Response.Charset = "utf-8"
Response.ContentType="text/xml"
Response.Write("<?xml version=""1.0"" encoding=""utf-8"" ?>"&vbcrlf)
Response.Write("<rss version="""&year(now())&right("0"&month(now()),2)&right("0"&day(now()),2)&right("0"&hour(now()),2)&".0"">"&vbcrlf)
Response.Write("<channel>"&vbcrlf)
Response.Write("<title>"&ew_mc&"RSS/XML</title>"&vbcrlf)
Response.Write("<link>"&e_tur&"</link>"&vbcrlf)
Response.Write("<description>"&ew_nr&"</description>"&vbcrlf)
Response.Write("<category>XML</category>"&vbcrlf)
Response.Write("<language>zh-cn</language>"&vbcrlf)
Response.Write("<docs>"&e_tur&s_drplug&"AsaiRss/rss.xml</docs>"&vbcrlf)
Response.Write("<generator>"&ew_zt&"</generator>"&vbcrlf)
Response.Write("<webMaster>"&ew_lr&"</webMaster>"&vbcrlf)
Response.Write("<managingEditor>"&ew_le&"</managingEditor>"&vbcrlf)
Response.Write("<pubDate>"&Now()&"</pubDate>"&vbcrlf)
Response.Write("<lastBuildDate>"&Now()&"</lastBuildDate>"&vbcrlf)
Response.Write("<ttl>"&g_pgls&"</ttl>"&vbcrlf)
Response.Write("<copyright>Copyright "&year(now())&" Www.Asai.Wang.</copyright>"&vbcrlf)
'@@0ai_id,1ai_sn,2ai_bt,3ai_tm,4ai_hi,5ai_xi,6ai_us,7ai_up,8ai_ss,9ai_xy,10ai_ef,11ai_ep,12ai_um,13ai_el,14ai_px,15ai_jg,16ai_jy,17ai_t1,18ai_t2,19ai_oy,20ai_oz,21ai_bd,22ai_bc,23ai_ee,24ai_jj,25ai_eq,26ai_cs,27ai_yy,28ai_mm
gysax=split(earr(0,s_umqb),g_gx)
for gysi=0 to ubound(gysax)
gysay=split(gysax(gysi),g_gy)
Response.Write("<item>"&vbcrlf)
Response.Write("<guid>"&gysay(0)&"</guid>"&vbcrlf)
Response.Write("<title>"&gysay(2)&"</title>"&vbcrlf)
Response.Write("<link>"&e_tur&eshref(esnk(gysay(11))&g_urg&esnf(gysay(10))&g_urg&s_umxx&g_urg&gysay(1)&g_urz,1)&"</link>"&vbcrlf)
Response.Write("<description><![CDATA["&esnr(gysay(8))&"]]></description>"&vbcrlf)
Response.Write("<author>"&ew_mc&"</author>"&vbcrlf)
Response.Write("<pubDate>"&gysay(3)&"</pubDate>"&vbcrlf)
Response.Write("<source>"&gysay(1)&"</source>"&vbcrlf)
Response.Write("<category>"&gysay(10)&"</category>"&vbcrlf)
Response.Write("<comments>"&e_tur&eshref(esnk(gysay(11))&g_urg&esnf(gysay(10))&g_urg&s_umxx&g_urg&gysay(1)&g_urz,1)&"</comments>"&vbcrlf)
Response.Write("</item>"&vbcrlf)
next
Response.Write("</channel>"&vbcrlf)
Response.Write("</rss>")
%><!--#include file="../../AsaiInc/incma.asp"-->